services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql
    restart: unless-stopped
    env_file: [ .env.docker ]
    volumes:
      - database-mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: is207.q13:backend-latest
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: [ .env.docker ]
    volumes:
      - ./backend:/app:cached
      - backend-vendor:/app/vendor
    depends_on:
      mysql:
        condition: service_healthy
    command: |
      sh -c "
        sleep 10 &&
        php artisan key:generate --force ;
        php artisan migrate --force ;
        php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "${LARAVEL_PORT:-8000}:8000"

  frontend:
    image: is207.q13:frontend-latest
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    env_file: [ .env.docker ]
    command: [ "npm", "run", "dev", "--", "--host" ]
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
    ports:
      - "${FRONTEND_PORT:-5173}:5173"

volumes:
  backend-vendor:
  frontend-node-modules:
  backend-node-modules:
  database-mysql:

# docker compose up -d
# docker compose down -v
# docker system prune -a